---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: bash:latest
            command:
            - /bin/bash
            - -c
            - echo "Hello world"
          restartPolicy: OnFailure