apiVersion: v1
kind: Pod
metadata:
  name: app-multi-containers
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - name: nginx-server
      image: nginx:latest
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
    - name: debian-writer
      image: debian:latest
      command: ["/bin/sh", "-c"]
      args:
        - >
          while true; do
            date >> /html/index.html;
            echo "<br>" >> /html/index.html;
            sleep 1;
          done
      volumeMounts:
        - name: html
          mountPath: /html
