---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
    run: demo
spec:
  containers:
    - name: app
      image: gcr.io/k8s-k3s/demo:v1.0.0
      ports:
        - containerPort: 8000
          name: http
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8000
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /ready
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 1
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
  volumes:
    - name: cache-volume
      emptyDir: {}
